#!/bin/bash

echo '#!/bin/bash

if which mongosh > /dev/null 2>&1; then
  mongo_init_bin='mongosh'
else
  mongo_init_bin='mongo'
fi
"${mongo_init_bin}" <<EOF
use admin
db.auth("unifi", "unifi")
db.createUser({
  user: "unifi",
  pwd: "unifi",
  roles: [
    { db: "unifi", role: "dbOwner" },
    { db: "unifi_stat", role: "dbOwner" },
    { db: "unifi_audit", role: "dbOwner" }
  ]
})
EOF' > init-mongo.sh
