#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

# Prepare an initialization script that restores the dump file
mkdir -vp initdb.d
mv -v unifi.archive initdb.d
#do the bash file to restore and exit once done
cat - >initdb.d/zz_unifi_restore.sh <<'EOS'
mongosh --eval 'db.dropDatabase();' unifi
mongorestore --archive=/docker-entrypoint-initdb.d/unifi.archive
exit 0
EOS

# once we exit we remove initdb.d
trap 'rm -rfv initdb.d/' EXIT

# we start a container to initiate a database and load the dump
# at the end of unifi_restore.sh the dump is loaded and 
# we exit the container
podman run \
  --rm \
  --interactive \
  --network=none \
  --volume ./initdb.d:/docker-entrypoint-initdb.d:z \
  --volume mongo-app:/data/db:Z \
  --replace --name=restore_db \
  ${MONGO_IMAGE}
